### ISSUE TITLE
Network importer fails with duplicate IP when utilizing a device from the onboarding plugin

### ISSUE THREAD

**Issue by nniehoff** [networktocode/network-importer#158]
### Environment
* Python version:  3.7.9
* Network Importer version:  2.0.0-beta3

When running network-importer on a device which was added by the onboarding plugin the IP address fails to be added by network importer as it has already been added.  I'm not sure if this is a bug with the onboarding plugin or network importer, but the interface was added by the onboarding plugin as `vlan 6` but network importer wants to add the IP to a device `Vlan6` this fails as it has already been added.  Changing the name of the interface from the onboarding plugin from `vlan 6` to `Vlan6` is a workaround for the moment, but the 2 plugins should be consistent.  The following error is from Network Importer:

```
2020-12-26 19:47:16,275 - network-importer - INFO - Created interface Vlan6 (126) in NetBox
2020-12-26 19:47:16,275 - diffsync.helpers - ERROR - 2020-12-26 19:47.16 [error    ] Failed to create ip_address {'address': '10.12.48.28/24'} - it already exists! [diffsync.helpers] action=create diffs={'+': {'interface_name': 'Vlan6', 'device_name': 'ciscosw2'}} dst=<Netbox> flags=<DiffSyncFlags.NONE: 0> model=ip_address src=<Network> status=error unique_id=192.168.48.2/24
```

### Steps to Reproduce
1.  Import device with Network Importer (Cisco SG300 in my case)
2.  Device gets added with IP on vlan 6
3.  Run network-importer apply, network importer fails with IP already exists.

### Expected Behavior
The IP should not be re-added by network importer

### Observed Behavior
IP added by the onboarding plugin was for interface `vlan 6` but network-importer wants to add the IP address to a new interface it creates `Vlan6`

**Comment by nniehoff** [comment]
The interface name from the switch is `vlan 6` therefore I believe the bug is actually in network-importer in this case.

**Comment by jvanderaa** [comment]
@nniehoff let's test with the latest installations. I ran the test and was successful all the way through with a Cisco 3750G.
