### ISSUE TITLE
ObjectNotFound when Device is Unreachable

### ISSUE THREAD

**Issue by rickdonato** [networktocode/network-importer#188]
In some situations the device may not be added to the `network` model i.e. due to the being unreachable or the hostname being incorrect upon the device. This will result in the device being present in the `sot` model and not the `network` model. At the point of sync the device is removed from the `sot` model, but the child objects cannot be updated because the parent device object is not present. Resulting in:
```
File "/opt/rick/venv/network-importer-XsxMQK7s-py3.6/lib/python3.6/site-packages/diffsync/__init__.py", line 567, in get
    raise ObjectNotFound(f"{modelname} {uid} not present in {self.name}")
diffsync.exceptions.ObjectNotFound: device rtr001 not present in Netbox
```

**Comment by dgarros** [comment]
Fixed in #189
