### ISSUE TITLE
Device Names that begin with a number need to be quoted

### ISSUE THREAD

**Issue by jvanderaa** [networktocode/network-importer#197]
### Environment
* Python version:  3.7.7
* Network Importer version: 2.0.0b4

### Steps to Reproduce
1. Enter a device that starts with numbers (`1234-SW1)
2. Run importer
3. Batfish errors appear

### Expected Behavior

Get the device on boarded

### Observed Behavior

Batfish error.

### Resolution

In reviewing the batfish issue, they pointed at https://pybatfish.readthedocs.io/en/latest/specifiers.html#general-notes-on-the-grammar. This indicates that a device that begins with a number must be quoted `"`. It is OK also to have quotes on non numeric devices. Fix: on the search for nodes add in escaped quotes.

**Comment by armartirosyan** [comment]
Fixed with PR #198
