### ISSUE TITLE
Add support for Nautobot 1.2

### ISSUE THREAD

**Issue by dgarros** [networktocode/network-importer#245]
### Environment
* Python version:  3.7
* Network Importer version:  3.0.1

### Proposed Functionality
Nautobot 1.2 is around the corner, with the first beta already available on pypi
I don't expect any major issue but it would be good to run the CI pipeline on both 1.1.5 and 1.2.0 to be sure.

**Comment by chadell** [comment]
it's already in the CI pipeline
